Logging persistence
UCY-Team/yeovil_microsoft_cognitive_ai pull request #116
Opened 2017-05-10 15:00 UTC by jsjlewis96

2017-05-10 18:06 UTC, Mattihew requested changes
lots of little comments

2017-05-10 18:06 UTC, Mattihew commented on ymca/src/main/java/endpoints/LoggingEndpoint.java
> +						messageArray.put(message);
this whole for loop can be replaced with `new JSONArray(messageQueue);`

2017-05-10 18:06 UTC, Mattihew commented on ymca/src/main/java/endpoints/LoggingEndpoint.java
> +	public static void log(final LogMessage logMessage)
add javadoc.

2017-05-10 18:06 UTC, Mattihew commented on ymca/src/main/java/endpoints/LoggingEndpoint.java
> +	public static void log(final LogMessage logMessage, final boolean queue)
update javadoc to reflect code changes.

2017-05-10 18:06 UTC, Mattihew commented on ymca/src/main/java/endpoints/LoggingEndpoint.java
> +	private static void queueMessageToAll(final LogMessage logMessage)
javadoc

2017-05-10 18:06 UTC, Mattihew commented on ymca/src/main/java/endpoints/LoggingEndpoint.java
> +		LoggingEndpoint.messages.put(logMessage.getSessionId(), messageQueue);
only need to put if `messageQueue` was originaly null

2017-05-10 18:06 UTC, Mattihew commented on ymca/src/main/java/endpoints/LoggingEndpoint.java
> +	public static SortedSet<LogMessage> getMessages(final String sessionId)
method does not need to be public now that servlet is gone. as method is so small might as well remove it.

2017-05-10 18:06 UTC, Mattihew commented on ymca/src/main/java/endpoints/LoggingEndpoint.java
> +					endpoint.session.getBasicRemote().sendText(message.toJSONString());
can be changed back to `ASyncRemote`

2017-05-10 18:06 UTC, Mattihew commented on ymca/src/main/java/endpoints/LoggingEndpoint.java
> +		endpoint.session.getAsyncRemote().sendText(jsonArray.toString());
as the `jsonArray` is only used to get a String, might as well make the method parameter a String

2017-05-10 18:06 UTC, Mattihew commented on ymca/src/main/java/endpoints/LoggingEndpoint.java
> +					endpoint.session.getBasicRemote().sendText(message.toJSONString());
as the `message` is only used to get a String, might as well make the method parameter a String

2017-05-10 18:06 UTC, Mattihew commented on ymca/src/main/java/models/LogMessage.java
> +		return new JSONObject()
cache result of this operation as it will be the same everytime. i.e
`if(jsonString == null){
 jsonString = value
}
return jsonString; `

2017-05-10 18:06 UTC, Mattihew commented on ymca/src/main/java/models/LogMessage.java
> +	public LogMessage(final String message)
javadoc on all methods

2017-05-10 18:06 UTC, Mattihew commented on ymca/src/main/java/models/LogMessage.java
> +
add Equals() method as this will be class will be used inside a Set

2017-05-10 18:06 UTC, Mattihew commented on ymca/src/main/java/listeners/HttpListener.java
> +    public HttpListener() {
delete constructor as default constructor is fine atm.

2017-05-10 18:06 UTC, Mattihew commented on ymca/src/main/java/listeners/HttpListener.java
> +         // TODO Auto-generated method stub
change `//TODO` to `//NOOP`

2017-05-11 12:56 UTC, jsjlewis96 commented on ymca/src/main/java/endpoints/LoggingEndpoint.java
> +					endpoint.session.getBasicRemote().sendText(message.toJSONString());
Makes more sense to me to only call .toJSONString in one place, rather than every time you want to call _logToClient_

2017-05-11 12:57 UTC, jsjlewis96 commented on ymca/src/main/java/endpoints/LoggingEndpoint.java
> +		endpoint.session.getAsyncRemote().sendText(jsonArray.toString());
Makes more sense to me to only call .toJSONString in one place, rather than every time you want to call _logToClient_

2017-05-11 13:03 UTC, Mattihew commented on ymca/src/main/java/endpoints/LoggingEndpoint.java
> +					endpoint.session.getBasicRemote().sendText(message.toJSONString());
agree

2017-05-11 13:04 UTC, Mattihew commented on ymca/src/main/java/endpoints/LoggingEndpoint.java
> +		endpoint.session.getAsyncRemote().sendText(jsonArray.toString());
method is only called in one place atm so would rather have method be as generic as posible

2017-05-11 13:22 UTC, Mattihew approved these changes

2017-05-11 13:23 UTC, merged